num_frames: 200
max_epoch: 53
batch_size: 150
uratio: 1
n_cpu: 4
test_step: 4
lr: 0.001
lr_decay: 0.97
putoff: 0.000351
train_list: /home/ljh/data/speaker/voxceleb2/train_list.txt
train_path: /home/ljh/data/speaker/voxceleb2/train/wav
eval_list: /home/ljh/data/speaker/voxceleb1/veri_test2.txt
eval_path: /home/ljh/data/speaker/voxceleb1/test/wav
musan_path: /home/ljh/data/speaker/Others/musan_split
rir_path: /home/ljh/data/speaker/Others/RIRS_NOISES/simulated_rirs
save_path: /home/ljh/exps/test_github
C: 1024
m: 0.2
s: 30
n_class: 5994
lb_samples_per_class: 20
eval: False
environment: False